---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: vito/oci-build-task

inputs:
  - name: context
    path: .
  - name: args
    path: args/
outputs:
  - name: image

params:
  CONTEXT:
  BUILD_ARGS_FILE: ""

caches:
  - path: cache

run: { path: build }
