name: Publish EIP-assigner Image

on:
  push:
    paths:
      - "eip-assigner/**"
      - ".github/workflows/publish-eip-assigner-image.yml"
    branches:
      - master
  schedule:
    - cron: "0 0 * * *" # Run every day at midnight

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository_owner }}/eip-assigner

jobs:
  build-latest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU #emulation support with QEMU to be able to build against more platforms.
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push the container to GitHub Container Registry using the latest tag
        uses: docker/build-push-action@v5.3.0
        with:
          context: .
          file: eip-assigner/Dockerfile
          platforms: |
            linux/amd64
            linux/arm64
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          push: true
          provenance: false
